import 'package:flutter/material.dart';
import 'pages/page_0.dart';
import 'pages/page_1.dart';
import 'pages/page_2.dart';
import 'pages/page_3.dart';
import 'pages/page_4.dart';
import 'pages/page_5.dart';
import 'pages/page_6.dart';
import 'pages/page_7.dart';
import 'pages/page_8.dart';
import 'pages/page_9.dart';
import 'pages/page_10.dart';
import 'pages/page_11.dart';
import 'pages/page_12.dart';
import 'pages/page_13.dart'; // Imported Page13
import 'pages/page_14.dart';
import 'pages/page_15.dart';
import 'pages/page_16.dart';
import 'pages/page_17.dart';
